name: Example Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Script
        run: echo "Hello from Job 1"
        
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run another script
        run: echo "Hello from Job 2"
